# wordpress-chart/templates/ingress.yaml
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: {{ .Values.ingress.annotations.sslRedirect | quote }}
    nginx.ingress.kubernetes.io/use-regex: {{ .Values.ingress.annotations.useRegex | quote }}
    nginx.ingress.kubernetes.io/proxy-read-timeout: {{ .Values.ingress.annotations.proxyReadTimeout | quote }}
    nginx.ingress.kubernetes.io/proxy-send-timeout: {{ .Values.ingress.annotations.proxySendTimeout | quote }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /(grafana|login)(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Values.ingress.grafanaService }}
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wordpress
            port:
              number: 80
{{- end }}